cp node_modules/leaflet/dist/leaflet.css src/assets
cp node_modules/leaflet/dist/images/* src/assets/images
cp node_modules/leaflet.markercluster/dist/leaflet.markercluster.js src/assets/js
cp node_modules/html2canvas/dist/html2canvas.min.js src/assets/js
cp node_modules/highcharts/highcharts.js src/assets/js
cp node_modules/highcharts/highcharts-more.js src/assets/js
cp node_modules/highcharts/modules/solid-gauge.js src/assets/js
cp node_modules/highcharts/modules/exporting.js src/assets/js
cp node_modules/highcharts/modules/offline-exporting.js src/assets/js
cp node_modules/highcharts/modules/drilldown.js src/assets/js
